const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 18.99,
    description: "A novel about the serious issues of rape and racial inequality.",
    cover: "/book-cover.jpg",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    price: 15.99,
    description: "A dystopian novel set in a totalitarian society under constant surveillance.",
    cover: "/book-cover.jpg",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 10.99,
    description: "A story about the young and mysterious millionaire Jay Gatsby.",
    cover: "/book-cover.jpg",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 12.99,
    description: "A romantic novel that also critiques the British landed gentry.",
    cover: "/book-cover.jpg",
  },
  {
    id: 5,
    title: "Moby Dick",
    author: "Herman Melville",
    price: 14.99,
    description: "A novel about the voyage of the whaling ship Pequod.",
    cover: "/book-cover.jpg",
  },
  {
    id: 6,
    title: "War and Peace",
    author: "Leo Tolstoy",
    price: 19.99,
    description: "A historical novel that chronicles the French invasion of Russia.",
    cover: "/book-cover.jpg",
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 13.99,
    description: "A story about the challenges of teenage life and alienation.",
    cover: "/book-cover.jpg",
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 16.99,
    description: "A fantasy novel about the journey of Bilbo Baggins.",
    cover: "/book-cover.jpg",
  },
  {
    id: 9,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    price: 17.99,
    description: "A psychological novel about morality and redemption.",
    cover: "/book-cover.jpg",
  },
  {
    id: 10,
    title: "The Odyssey",
    author: "Homer",
    price: 11.99,
    description: "An epic poem about the adventures of Odysseus.",
    cover: "/book-cover.jpg",
  },
]

const users = [
  {
    name: "1",
    nickname: "John Doe",
    balance: 100.0,
    avatar: "/profile-img.png",
    addresses: [
      {
        id: 1,
        receiver: "Jane Doe",
        tel: "1234567890",
        address: "123 Main St, Springfield, USA",
      },
      {
        id: 2,
        receiver: "John Smith",
        tel: "0987654321",
        address: "456 Elm St, Springfield, USA",
      },
    ],
    cart: [
      {
        id: 1,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 18.99,
        description: "A novel about the serious issues of rape and racial inequality.",
        cover: "/book-cover.jpg",
      },
      {
        id: 2,
        title: "1984",
        author: "George Orwell",
        price: 15.99,
        description: "A dystopian novel set in a totalitarian society under constant surveillance.",
        cover: "/book-cover.jpg",
      },
      {
        id: 3,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        price: 10.99,
        description: "A story about the young and mysterious millionaire Jay Gatsby.",
        cover: "/book-cover.jpg",
      },
    ],
    orders: [
      {
        receiver: "Jane Doe",
        tel: "1234567890",
        address: "123 Main St, Springfield, USA",
        date: "2023-10-01",
        totalPrice: 18.99,
        books: [
          {
            id: 1,
            title: "To Kill a Mockingbird",
            author: "Harper Lee",
            price: 18.99,
            description: "A novel about the serious issues of rape and racial inequality.",
            cover: "/book-cover.jpg",
          },
        ],
      },
    ],
  },
]

export { books, users }
